/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as PortalServicesRouteImport } from './routes/portal.services'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalPaymentsRouteImport } from './routes/portal.payments'
import { Route as PortalObservationsRouteImport } from './routes/portal.observations'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalFinanceRouteImport } from './routes/portal.finance'
import { Route as PortalFilesRouteImport } from './routes/portal.files'
import { Route as PortalDemandsRouteImport } from './routes/portal.demands'
import { Route as PortalCalendarRouteImport } from './routes/portal.calendar'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppServicesRouteImport } from './routes/app.services'
import { Route as AppServiceOrdersRouteImport } from './routes/app.service-orders'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppDemandsRouteImport } from './routes/app.demands'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppClientsIndexRouteImport } from './routes/app.clients.index'
import { Route as AppDemandsDemandIdRouteImport } from './routes/app.demands.$demandId'
import { Route as AppClientsClientIdRouteImport } from './routes/app.clients.$clientId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PortalServicesRoute = PortalServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPaymentsRoute = PortalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalObservationsRoute = PortalObservationsRouteImport.update({
  id: '/observations',
  path: '/observations',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFinanceRoute = PortalFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFilesRoute = PortalFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDemandsRoute = PortalDemandsRouteImport.update({
  id: '/demands',
  path: '/demands',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCalendarRoute = PortalCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PortalRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceOrdersRoute = AppServiceOrdersRouteImport.update({
  id: '/service-orders',
  path: '/service-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandsRoute = AppDemandsRouteImport.update({
  id: '/demands',
  path: '/demands',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppDemandsDemandIdRoute = AppDemandsDemandIdRouteImport.update({
  id: '/$demandId',
  path: '/$demandId',
  getParentRoute: () => AppDemandsRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AppClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/demands': typeof AppDemandsRouteWithChildren
  '/app/finance': typeof AppFinanceRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/service-orders': typeof AppServiceOrdersRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/portal/calendar': typeof PortalCalendarRoute
  '/portal/demands': typeof PortalDemandsRoute
  '/portal/files': typeof PortalFilesRoute
  '/portal/finance': typeof PortalFinanceRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/observations': typeof PortalObservationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/services': typeof PortalServicesRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/demands/$demandId': typeof AppDemandsDemandIdRoute
  '/app/clients/': typeof AppClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/demands': typeof AppDemandsRouteWithChildren
  '/app/finance': typeof AppFinanceRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/service-orders': typeof AppServiceOrdersRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/portal/calendar': typeof PortalCalendarRoute
  '/portal/demands': typeof PortalDemandsRoute
  '/portal/files': typeof PortalFilesRoute
  '/portal/finance': typeof PortalFinanceRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/observations': typeof PortalObservationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/services': typeof PortalServicesRoute
  '/app': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/demands/$demandId': typeof AppDemandsDemandIdRoute
  '/app/clients': typeof AppClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/signup': typeof SignupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/clients': typeof AppClientsRouteWithChildren
  '/app/demands': typeof AppDemandsRouteWithChildren
  '/app/finance': typeof AppFinanceRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/service-orders': typeof AppServiceOrdersRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/portal/calendar': typeof PortalCalendarRoute
  '/portal/demands': typeof PortalDemandsRoute
  '/portal/files': typeof PortalFilesRoute
  '/portal/finance': typeof PortalFinanceRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/observations': typeof PortalObservationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/services': typeof PortalServicesRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/clients/$clientId': typeof AppClientsClientIdRoute
  '/app/demands/$demandId': typeof AppDemandsDemandIdRoute
  '/app/clients/': typeof AppClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/portal'
    | '/signup'
    | '/app/activity'
    | '/app/calendar'
    | '/app/clients'
    | '/app/demands'
    | '/app/finance'
    | '/app/goals'
    | '/app/leads'
    | '/app/reports'
    | '/app/service-orders'
    | '/app/services'
    | '/app/settings'
    | '/app/team'
    | '/portal/calendar'
    | '/portal/demands'
    | '/portal/files'
    | '/portal/finance'
    | '/portal/login'
    | '/portal/observations'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/services'
    | '/app/'
    | '/portal/'
    | '/app/clients/$clientId'
    | '/app/demands/$demandId'
    | '/app/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/activity'
    | '/app/calendar'
    | '/app/demands'
    | '/app/finance'
    | '/app/goals'
    | '/app/leads'
    | '/app/reports'
    | '/app/service-orders'
    | '/app/services'
    | '/app/settings'
    | '/app/team'
    | '/portal/calendar'
    | '/portal/demands'
    | '/portal/files'
    | '/portal/finance'
    | '/portal/login'
    | '/portal/observations'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/services'
    | '/app'
    | '/portal'
    | '/app/clients/$clientId'
    | '/app/demands/$demandId'
    | '/app/clients'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/portal'
    | '/signup'
    | '/app/activity'
    | '/app/calendar'
    | '/app/clients'
    | '/app/demands'
    | '/app/finance'
    | '/app/goals'
    | '/app/leads'
    | '/app/reports'
    | '/app/service-orders'
    | '/app/services'
    | '/app/settings'
    | '/app/team'
    | '/portal/calendar'
    | '/portal/demands'
    | '/portal/files'
    | '/portal/finance'
    | '/portal/login'
    | '/portal/observations'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/services'
    | '/app/'
    | '/portal/'
    | '/app/clients/$clientId'
    | '/app/demands/$demandId'
    | '/app/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/services': {
      id: '/portal/services'
      path: '/services'
      fullPath: '/portal/services'
      preLoaderRoute: typeof PortalServicesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/payments': {
      id: '/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof PortalPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/observations': {
      id: '/portal/observations'
      path: '/observations'
      fullPath: '/portal/observations'
      preLoaderRoute: typeof PortalObservationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/finance': {
      id: '/portal/finance'
      path: '/finance'
      fullPath: '/portal/finance'
      preLoaderRoute: typeof PortalFinanceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/files': {
      id: '/portal/files'
      path: '/files'
      fullPath: '/portal/files'
      preLoaderRoute: typeof PortalFilesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/demands': {
      id: '/portal/demands'
      path: '/demands'
      fullPath: '/portal/demands'
      preLoaderRoute: typeof PortalDemandsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/calendar': {
      id: '/portal/calendar'
      path: '/calendar'
      fullPath: '/portal/calendar'
      preLoaderRoute: typeof PortalCalendarRouteImport
      parentRoute: typeof PortalRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/service-orders': {
      id: '/app/service-orders'
      path: '/service-orders'
      fullPath: '/app/service-orders'
      preLoaderRoute: typeof AppServiceOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demands': {
      id: '/app/demands'
      path: '/demands'
      fullPath: '/app/demands'
      preLoaderRoute: typeof AppDemandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients/': {
      id: '/app/clients/'
      path: '/'
      fullPath: '/app/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/app/demands/$demandId': {
      id: '/app/demands/$demandId'
      path: '/$demandId'
      fullPath: '/app/demands/$demandId'
      preLoaderRoute: typeof AppDemandsDemandIdRouteImport
      parentRoute: typeof AppDemandsRoute
    }
    '/app/clients/$clientId': {
      id: '/app/clients/$clientId'
      path: '/$clientId'
      fullPath: '/app/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppClientsRoute
    }
  }
}

interface AppClientsRouteChildren {
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppDemandsRouteChildren {
  AppDemandsDemandIdRoute: typeof AppDemandsDemandIdRoute
}

const AppDemandsRouteChildren: AppDemandsRouteChildren = {
  AppDemandsDemandIdRoute: AppDemandsDemandIdRoute,
}

const AppDemandsRouteWithChildren = AppDemandsRoute._addFileChildren(
  AppDemandsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppDemandsRoute: typeof AppDemandsRouteWithChildren
  AppFinanceRoute: typeof AppFinanceRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppServiceOrdersRoute: typeof AppServiceOrdersRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppDemandsRoute: AppDemandsRouteWithChildren,
  AppFinanceRoute: AppFinanceRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppReportsRoute: AppReportsRoute,
  AppServiceOrdersRoute: AppServiceOrdersRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalCalendarRoute: typeof PortalCalendarRoute
  PortalDemandsRoute: typeof PortalDemandsRoute
  PortalFilesRoute: typeof PortalFilesRoute
  PortalFinanceRoute: typeof PortalFinanceRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalObservationsRoute: typeof PortalObservationsRoute
  PortalPaymentsRoute: typeof PortalPaymentsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalServicesRoute: typeof PortalServicesRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCalendarRoute: PortalCalendarRoute,
  PortalDemandsRoute: PortalDemandsRoute,
  PortalFilesRoute: PortalFilesRoute,
  PortalFinanceRoute: PortalFinanceRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalObservationsRoute: PortalObservationsRoute,
  PortalPaymentsRoute: PortalPaymentsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalServicesRoute: PortalServicesRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
